/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion_frais_scolaires;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.time.LocalDateTime;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Geek Man
 */
public class Paiement extends javax.swing.JFrame {

    public static String eleveMat;
    
    Connexion_mysql mycon = new Connexion_mysql();
    
    private ResultSet Rs;
    String today;
    
    Map<String, String> matEleves = new HashMap<>();
    Map<String, String> matCaissiers = new HashMap<>();
    
    int rowsC;
    
    String Num_recu, NomEleve, NomCaissier, Libelle, Montant, Devise, Date_paiement, Annee_acad, matCaissier, matEleve;
    DefaultTableModel dt = new DefaultTableModel();
    
    public Paiement() {
        initComponents();
    }
    
    public Paiement(String eleveMat, String nomEleve, String matCaissier, String nomCaissier, String classe){
        this();
        lMatricule.setText(eleveMat);
        tMatcaissier.setText(matCaissier);
        tNamecaissier.setText(nomCaissier);
        jEleve.setText(nomEleve);
        tClasse.setText(classe);
        
        System.out.println(matCaissier);
        
        jButton4.setEnabled(false);
        jButton3.setEnabled(false);  
        jButton7.setEnabled(false);

        
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");  
        LocalDateTime now = LocalDateTime.now();
        
        today = dtf.format(now);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        tNum_recu = new javax.swing.JTextField();
        tNamecaissier = new javax.swing.JTextField();
        tLibelle = new javax.swing.JTextField();
        jEleve = new javax.swing.JTextField();
        tClasse = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tMontant = new javax.swing.JTextField();
        cDevise = new javax.swing.JComboBox<String>();
        jLabel9 = new javax.swing.JLabel();
        tAnnee = new javax.swing.JTextField();
        lMatricule = new javax.swing.JLabel();
        tMatcaissier = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dtpaiement = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        tChercher = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jCheck = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Paiement frais");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tNum_recu.setEditable(false);

        tNamecaissier.setEditable(false);

        jEleve.setEditable(false);

        tClasse.setEditable(false);

        jLabel2.setText("Num_reçu");

        jLabel3.setText("Caissier");

        jLabel4.setText("Eleve");

        jLabel5.setText("Libellé");

        jLabel6.setText("Montant");

        jLabel7.setText("Classe");

        jLabel8.setText("Devise");

        jButton1.setText("Select eleve");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cDevise.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "USD", "CDF" }));

        jLabel9.setText("Année academique");

        tMatcaissier.setText("00");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lMatricule))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(tMatcaissier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tNamecaissier, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tAnnee)
                    .addComponent(tClasse, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tLibelle, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tNum_recu)
                    .addComponent(tMontant, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jEleve, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cDevise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tNum_recu)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tMatcaissier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tNamecaissier)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lMatricule, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jEleve)
                        .addComponent(jLabel4)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tLibelle)
                    .addComponent(jLabel5))
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tMontant))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tClasse)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(cDevise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tAnnee)
                    .addComponent(jLabel9)))
        );

        dtpaiement.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dtpaiement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dtpaiementMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dtpaiement);

        jButton5.setText("Rechercher");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(tChercher, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tChercher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setBackground(new java.awt.Color(0, 153, 0));
        jButton2.setText("Ajouter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 204));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Modifier");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Supprimer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setText("Reinitialiser");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText(" Imprimmer reçu");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jCheck.setText("Date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheck)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jCheck)
                                .addGap(13, 13, 13))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void afficherPaiement() {
        
        String query = "SELECT Num_recu,eleve_Mat,caissier_Mat,NOM,NOM_CAISSIER,Libelle,Montant,Annee_acad,Devise,Date_paiement " +
                       "FROM eleves,caissiers,recus " +
                       "WHERE recus.eleve_Mat=eleves.Matricule_Eleve AND recus.caissier_Mat=caissiers.Matricule_caissier";
        
        Rs = mycon.getResultat(query);
        dt.setRowCount(0);
        rowsC = 1;
        matEleves.clear();
        matCaissiers.clear();
        try{
            while(Rs.next()){
                Num_recu = Rs.getString("Num_recu");
                NomEleve = Rs.getString("NOM");
                NomCaissier = Rs.getString("NOM_CAISSIER");
                Libelle = Rs.getString("Libelle");
                Montant = Rs.getString("Montant");
                Annee_acad = Rs.getString("Annee_acad");
                Devise = Rs.getString("Devise");
                Date_paiement = Rs.getString("Date_paiement");
                
                matCaissier = Rs.getString("caissier_Mat");
                matEleve = Rs.getString("eleve_Mat");
                
                matEleves.put(NomEleve, matEleve);
                matCaissiers.put(NomCaissier, matCaissier);
                
                rowsC++;
                
                Object[] Table = {Num_recu,NomEleve,NomCaissier,Libelle,Montant,Annee_acad, Devise, Date_paiement};
                dt.addRow(Table);
            }
            tNum_recu.setText(String.valueOf(rowsC));
            System.out.println(matEleves + " " + matCaissiers);
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Erreur d'affichage\n"+ex.getMessage());
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Select_eleve(tMatcaissier.getText(), tNamecaissier.getText()).show();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        dt= new DefaultTableModel();
        dt.addColumn("Num_recu");
        dt.addColumn("Nom_Elève");
        dt.addColumn("Nom_Caissier");
        dt.addColumn("Libelle");
        dt.addColumn("Montant");
        dt.addColumn("Année academique");
        dt.addColumn("Devise");
        dt.addColumn("Date de paiement");
        dtpaiement.setModel(dt);
        
        afficherPaiement();
    }//GEN-LAST:event_formWindowOpened

    private void dtpaiementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dtpaiementMouseClicked
        try{
            DefaultTableModel dl = (DefaultTableModel)dtpaiement.getModel();
            int index = dtpaiement.getSelectedRow();
            jButton3.setEnabled(true);
            jButton2.setEnabled(false);
            jButton4.setEnabled(true);
            jButton7.setEnabled(true);
        
            tNum_recu.setText(dl.getValueAt(index, 0).toString());
            lMatricule.setText(matEleves.get(dl.getValueAt(index, 1).toString()));
            tMatcaissier.setText(matCaissiers.get(dl.getValueAt(index, 2).toString()));
            jEleve.setText(dl.getValueAt(index, 1).toString());
            tLibelle.setText(dl.getValueAt(index, 3).toString());
            tMontant.setText(dl.getValueAt(index, 4).toString());
            tAnnee.setText(dl.getValueAt(index, 5).toString());
            cDevise.setSelectedItem(dl.getValueAt(index, 6).toString());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Erreur sectionnez bien " + e.getMessage());
        }
        
    }//GEN-LAST:event_dtpaiementMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jButton3.setEnabled(false);
        jButton2.setEnabled(true);
        jButton4.setEnabled(false);
        jButton7.setEnabled(false);
        
        jEleve.setText("");
        lMatricule.setText("");
        tLibelle.setText("");
        tMontant.setText("");
        tClasse.setText("");
        tAnnee.setText("");
        
        afficherPaiement();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(!tLibelle.getText().equals("") || !tMontant.getText().equals("") || !tClasse.getText().equals("") || !tAnnee.getText().equals("")){
            if(JOptionPane.showConfirmDialog(this,"Voulez vous Ajouter cet Enregistrement","Confirmation",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
                String query = "INSERT INTO recus VALUES('" + tNum_recu.getText() + "','" +
                                                          lMatricule.getText() + "','" + 
                                                          tMatcaissier.getText() + "','" +
                                                          tLibelle.getText() + "','" +
                                                          tMontant.getText() + "','" +
                                                          tAnnee.getText() + "','" +
                                                          cDevise.getSelectedItem()+ "','" +
                                                          today + "')";
            
            
                mycon.getResultat(query);
                afficherPaiement();
            }
        }
        else JOptionPane.showMessageDialog(null,"Veuillez remplir tout les champs");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(JOptionPane.showConfirmDialog(this,"Voulez vous supprimer cet enregistrement","Confirmation",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            String query = "DELETE FROM recus WHERE Num_recu='" + tNum_recu.getText() + "'";
            mycon.getResultat(query);
            afficherPaiement();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String query = "UPDATE recus SET caissier_Mat='" + tMatcaissier.getText() + "', eleve_Mat='" + lMatricule.getText() + "', Libelle='" + tLibelle.getText() +
                                                  "', Montant='" + tMontant.getText() + "' WHERE Num_recu='" + tNum_recu.getText() + "'";
        
        mycon.getResultat(query);
        afficherPaiement();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String tche=tChercher.getText();
        String query = "SELECT Num_recu,eleve_Mat,caissier_Mat,NOM,NOM_CAISSIER,Libelle,Montant,Annee_acad,Devise,Date_paiement " +
                       "FROM eleves,caissiers,recus " +
                       "WHERE recus.eleve_Mat=eleves.Matricule_Eleve AND recus.caissier_Mat=caissiers.Matricule_caissier AND " +
                       "(Num_recu='" + tche + "' OR eleve_Mat='" + tche + "' OR eleve_Mat='" + tche + "' OR NOM='" +
                       tche + "' OR NOM_CAISSIER='" + tche + "' OR Libelle='" + tche + "' OR Annee_acad='" + tche + "' OR Devise='" + tche + "' OR Montant='" + tche + "')";
        
        String query1 = "SELECT Num_recu,eleve_Mat,caissier_Mat,NOM,NOM_CAISSIER,Libelle,Montant,Annee_acad,Devise,Date_paiement " +
                       "FROM eleves,caissiers,recus " +
                       "WHERE recus.eleve_Mat=eleves.Matricule_Eleve AND recus.caissier_Mat=caissiers.Matricule_caissier AND Date_paiement='"+
                       tche + "'";
        
        if(jCheck.isSelected()){
            Rs = mycon.getResultat(query1);
        }
        else{
            Rs = mycon.getResultat(query);
        }
        dt.setRowCount(0);
        
        try{
            while(Rs.next()){
                Num_recu = Rs.getString("Num_recu");
                NomEleve = Rs.getString("NOM");
                NomCaissier = Rs.getString("NOM_CAISSIER");
                Libelle = Rs.getString("Libelle");
                Montant = Rs.getString("Montant");
                Annee_acad = Rs.getString("Annee_acad");
                Devise = Rs.getString("Devise");
                Date_paiement = Rs.getString("Date_paiement");
                
                
                Object[] Table = {Num_recu,NomEleve,NomCaissier,Libelle,Montant,Annee_acad, Devise, Date_paiement};
                dt.addRow(Table);
            }
            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Erreur d'affichage\n"+ex.getMessage());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Connexion_mysql mycon = new Connexion_mysql();
    
        ResultSet Rs;
    
        String Sexe = null, Classe = null;
        
        String query = "SELECT * FROM eleves WHERE Matricule_Eleve='" + lMatricule.getText() + "'";
        Rs = mycon.getResultat(query);
        query = "SELECT * FROM caissiers WHERE Matricule_caissier='" + tMatcaissier.getText() + "'";
        try{
            while(Rs.next()){
                matEleve = Rs.getString("Matricule_Eleve");
                NomEleve = Rs.getString("NOM")+ " " + Rs.getString("POSTNOM") + " " + Rs.getString("PRENOM");
                Sexe = Rs.getString("SEXE");
                Classe = Rs.getString("CLASSE");
            }
            Rs = mycon.getResultat(query);
            while(Rs.next()){
                matCaissier = Rs.getString("Matricule_caissier");
                NomCaissier = Rs.getString("NOM_CAISSIER") + " " + Rs.getString("POSTNOM_CAISSIER") + " " + Rs.getString("PRENOM_CAISSIER");
            }
            
            Num_recu = tNum_recu.getText();
            Libelle = tLibelle.getText();
            Montant = tMontant.getText();
            Annee_acad = tAnnee.getText();
            Devise = cDevise.getSelectedItem().toString();
            Date_paiement = today;
                    
            new Recu(Num_recu, matEleve, NomEleve, Montant, Libelle, Date_paiement, Classe, Devise, Annee_acad, matCaissier, NomCaissier, Sexe).show();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Erreur de selection\n"+ex.getMessage());
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paiement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paiement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paiement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paiement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paiement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cDevise;
    private javax.swing.JTable dtpaiement;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBox jCheck;
    private static javax.swing.JTextField jEleve;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lMatricule;
    private javax.swing.JTextField tAnnee;
    private javax.swing.JTextField tChercher;
    private javax.swing.JTextField tClasse;
    private javax.swing.JTextField tLibelle;
    private javax.swing.JLabel tMatcaissier;
    private javax.swing.JTextField tMontant;
    private javax.swing.JTextField tNamecaissier;
    private javax.swing.JTextField tNum_recu;
    // End of variables declaration//GEN-END:variables

}
